// src/constants/collegesAndMajors.ts
export interface College {
  name: string;
  code: string;
  majors: string[];
}

export const COLLEGES_AND_MAJORS: College[] = [
  {
    name: "College of Agriculture & Life Sciences (CALS)",
    code: "CALS",
    majors: [
      "Agricultural Sciences",
      "Animal Science",
      "Biological Engineering",
      "Biological Sciences",
      "Biology & Society",
      "Biometry & Statistics",
      "Communication",
      "Development Sociology",
      "Entomology",
      "Environment & Sustainability",
      "Environmental Engineering",
      "Food Science",
      "Global Development",
      "Global & Public Health Sciences",
      "Information Science",
      "Landscape Architecture",
      "Nutritional Sciences",
      "Plant Sciences",
      "Viticulture & Enology",
      "Science of Earth Systems (EAS track via CALS)",
    ],
  },
  {
    name: "College of Architecture, Art, and Planning (AAP)",
    code: "AAP",
    majors: [
      "Architecture (B.Arch)",
      "Art (B.F.A.)",
      "Urban & Regional Studies",
    ],
  },
  {
    name: "College of Arts & Sciences (A&S)",
    code: "AS",
    majors: [
      "Africana Studies",
      "American Studies",
      "Anthropology",
      "Archaeology",
      "Asian Studies",
      "Astronomy",
      "Biology & Society",
      "Biological Sciences",
      "Chemistry",
      "China & Asia Pacific Studies",
      "Classics",
      "Comparative Literature",
      "Computer Science",
      "Earth & Atmospheric Sciences",
      "Economics",
      "English",
      "Environment & Sustainability",
      "Feminist, Gender & Sexuality Studies",
      "French",
      "German Studies",
      "Government",
      "History",
      "History of Architecture",
      "History of Art",
      "Information Science",
      "Italian",
      "Linguistics",
      "Mathematics",
      "Music",
      "Near Eastern Studies",
      "Philosophy",
      "Physics",
      "Psychology",
      "Religious Studies",
      "Science & Technology Studies",
      "Sociology",
      "Spanish",
      "Statistical Science",
      "College Scholar (self-designed major)",
    ],
  },
  {
    name: "College of Engineering",
    code: "ENG",
    majors: [
      "Biological Engineering",
      "Biomedical Engineering",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Science",
      "Earth & Atmospheric Sciences",
      "Electrical & Computer Engineering",
      "Engineering Physics",
      "Environmental Engineering",
      "Information Science, Systems & Technology (ISST)",
      "Materials Science & Engineering",
      "Mechanical Engineering",
      "Operations Research & Engineering (OR&E)",
    ],
  },
  {
    name: "College of Human Ecology",
    code: "HUMEC",
    majors: [
      "Design + Environmental Analysis",
      "Fashion Design and Management",
      "Fiber Science & Apparel Design",
      "Global & Public Health Sciences",
      "Human Biology, Health & Society",
      "Human Development",
      "Nutritional Sciences",
    ],
  },
  {
    name: "School of Industrial & Labor Relations (ILR)",
    code: "ILR",
    majors: ["Industrial & Labor Relations"],
  },
  {
    name: "SC Johnson College of Business",
    code: "JCB",
    majors: ["Applied Economics & Management (AEM)", "Hotel Administration"],
  },
  {
    name: "Brooks School of Public Policy",
    code: "BSP",
    majors: ["Public Policy", "Health Care Policy", "Policy Analysis"],
  },
];
